modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://discord.gg/Z8qMNugsZq"
license = "All Rights Reserved"
[[mods]]
modId = "tinyfoes"
version = "${version}"
displayName = "Tiny Foes"
authors = "Lgowz"
displayURL = "https://curseforge.com/minecraft/mc-mods/tinyfoes"
description = '''
Tiny Foes adds the baby versions of most vanilla enemies!
'''
#logoFile = "assets/tinyallies/icon.png"

[[dependencies.tinyfoes]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinyfoes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinyfoes]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.85,)"
ordering = "AFTER"
side = "BOTH"