modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "tinyfoes"
version = "${version}"
displayName = "Tiny Foes"
authors = "Lgowz"
description = '''
Tiny Allies adds tamable baby versions of the classic vanilla monsters!
'''
#logoFile = "assets/tinyallies/icon.png"

[[dependencies.tinyfoes]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinyfoes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinyfoes]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.85,)"
ordering = "AFTER"
side = "BOTH"