modLoader = "javafml"
loaderVersion = "[#,)"
issueTrackerURL = "${issue_tracker}"
license = "${license}"
[[mods]]
modId = "${archives_base_name}"
version = "${version}"
displayName = "${display_name}"
authors = "${authors}"
displayURL = "${home_page}"
description = "${description}"
logoFile = "assets/${archives_base_name}/icon.png"

[[dependencies.tinyfoes]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinyfoes]]
modId = "forge"
mandatory = true
versionRange = "[${forgeloader_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinyfoes]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"