modLoader = "javafml"
loaderVersion = "[${forge_loader_version},)"
issueTrackerURL = "https://discord.gg/Z8qMNugsZq"
license = "All Rights Reserved"
[[mods]]
modId = "tinyapi"
version = "${version}"
displayName = "Tiny Foes"
authors = "Lgowz"
displayURL = "https://curseforge.com/minecraft/mc-mods/tinyapi"
description = '''
Tiny Foes adds the baby versions of most vanilla enemies!
'''
#logoFile = "assets/tinyapi/icon.png"

[[dependencies.tinyapi]]
modId = "forge"
mandatory = true
versionRange = "[${forge_loader_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinyapi]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinyapi]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"