modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory
issueTrackerURL= "https://github.com/lgow/endofherobrine/issues/" #optional
logoFile="endofherobrine.png" #optional
license="All Rights Reserved"

[[mods]]
displayName="The End of Herobrine"
version= "${file.jarVersion}"
modId="endofherobrine"
credits="Uncrossed Arms Villagers(Jappa) - TheBartman"
authors="lgow" #optional
#updateJSONURL="https://github.com/lgow/endofherobrine/updates.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/endofherobrine" #homepage
description="" #mandatory