architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/tinyfoes.accesswidener")
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabricloader_version}"
    modApi "dev.architectury:architectury:${rootProject.architectury_version}"
    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-common:${rootProject.forgeconfigapiport_version}"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            pom {
                name = rootProject.display_name
                description = rootProject.description
                licenses {
                    license {
                        name = rootProject.license
                    }
                }
                developers {
                    developer {
                        id = 'lgow'
                        name = rootProject.authors
                    }
                }
                scm {
                    connection = 'scm:git:https://github.com/lgow/tinyfoes.git'
                    developerConnection = 'scm:git:ssh://github.com/lgow/tinyfoes.git'
                    url = 'https://github.com/lgow/tinyfoes'
                }
            }
        }
    }
}
